In [0]:
import numpy as np

In [0]:
simple_list = [1,2,3]

In [0]:
np.array(simple_list)

array([1, 2, 3])

In [0]:
list_of_lists = [[1,2,3], [4,5,6], [7,8,9]]

In [0]:
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
np.arange(0,21,5)

array([ 0,  5, 10, 15, 20])

In [0]:
ed = np.zeros(100)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [0]:
np.ones((4,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [0]:
np.linspace(0,20,10)

array([  0.        ,   2.22222222,   4.44444444,   6.66666667,
         8.88888889,  11.11111111,  13.33333333,  15.55555556,
        17.77777778,  20.        ])

In [0]:
a = np.eye(5)

In [0]:
np.random.rand(3,2)

array([[ 0.22040679,  0.8007732 ],
       [ 0.05132687,  0.68783682],
       [ 0.77533236,  0.15193409]])

In [0]:
a = np.random.randn(2,3)

In [0]:
np.random.randint(5,20,10)

array([15,  9, 14, 14, 15,  6,  7, 10,  6, 11])

In [0]:
sample_array = np.arange(30)

In [0]:
rand_array = np.random.randint(0,100,20)

In [0]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [0]:
rand_array.argmin()

18

In [0]:
sample_array.shape

(30,)

In [0]:
sample_array.reshape(1,30)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [0]:
sample_array.reshape(30,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29]])

In [0]:
sample_array.dtype

dtype('int32')

In [0]:
a.T

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [0]:
a.T

array([[ 0.5496091 , -0.54812681],
       [ 1.36442643, -0.12962563],
       [-0.61062758, -0.64242844]])

In [0]:
sample_array = np.arange(10,21)

In [0]:
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [0]:
sample_array[8]

18

In [0]:
sample_array[[2,5]]

array([12, 15])

In [0]:
sample_array[1:2] = 100

In [0]:
sample_array

array([ 10, 100,  12,  13,  14,  15,  16,  17,  18,  19,  20])

In [0]:
sample_array = np.arange(10,21)

In [0]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [0]:
sample_array = np.arange(10,21)
                        
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [0]:
subset_sample_array = sample_array[0:7]

subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [0]:
subset_sample_array[:]=1001

In [0]:
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

In [0]:
sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001,   17,   18,   19,   20])

In [0]:
copy_sample_array = sample_array.copy()

In [0]:
copy_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001,   17,   18,   19,   20])

In [0]:
copy_sample_array[:]=10
copy_sample_array

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [0]:
sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001,   17,   18,   19,   20])

In [0]:
sample_matrix = np.array(([50,20,1,23], [24,23,21,32], [76,54,32,12], [98,6,4,3]))

In [0]:
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 32],
       [76, 54, 32, 12],
       [98,  6,  4,  3]])

In [0]:
sample_matrix[0][3]

23

In [0]:
sample_matrix[0,3]

23

In [0]:
sample_matrix[3,:]

array([98,  6,  4,  3])

In [0]:
sample_matrix[3]

array([98,  6,  4,  3])

In [0]:
sample_matrix = np.array(([50,20,1,23,34], [24,23,21,32,34], [76,54,32,12,98], [98,6,4,3,67], [12,23,34,56,67]))

In [0]:
sample_matrix

array([[50, 20,  1, 23, 34],
       [24, 23, 21, 32, 34],
       [76, 54, 32, 12, 98],
       [98,  6,  4,  3, 67],
       [12, 23, 34, 56, 67]])

In [0]:
sample_matrix[:,(1,3)]

array([[20, 23],
       [23, 32],
       [54, 12],
       [ 6,  3],
       [23, 56]])

In [0]:
sample_matrix[:,(3,1)]

array([[23, 20],
       [32, 23],
       [12, 54],
       [ 3,  6],
       [56, 23]])

In [0]:
sample_array=np.arange(1,31)

In [0]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [0]:
bool = sample_array < 10

In [0]:
sample_array[bool]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
sample_array[sample_array <10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
a=11

In [0]:
sample_array[sample_array < a]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
sample_array + sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [0]:
sample_array / sample_array

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.])

In [0]:
10/sample_array

array([ 10.        ,   5.        ,   3.33333333,   2.5       ,
         2.        ,   1.66666667,   1.42857143,   1.25      ,
         1.11111111,   1.        ,   0.90909091,   0.83333333,
         0.76923077,   0.71428571,   0.66666667,   0.625     ,
         0.58823529,   0.55555556,   0.52631579,   0.5       ,
         0.47619048,   0.45454545,   0.43478261,   0.41666667,
         0.4       ,   0.38461538,   0.37037037,   0.35714286,
         0.34482759,   0.33333333])

In [0]:
sample_array + 1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [0]:
np.var(sample_array)

74.916666666666671

In [0]:
array = np.random.randn(6,6)

In [0]:
array

array([[-0.04434275,  0.81587138,  1.4551598 , -2.63516776,  1.18967678,
        -0.7616773 ],
       [ 3.15209842, -1.03710081, -1.92199594,  1.13267871,  1.52520249,
        -1.49360324],
       [ 0.92673156,  0.68729547,  1.13991227,  0.92487789,  0.56836181,
        -0.89949646],
       [-0.06886363, -0.14743934, -2.39224556, -0.67836918, -0.47092714,
         0.06363147],
       [ 1.19718443,  0.96307634,  1.67437581, -1.24063201,  0.30934432,
         0.88432444],
       [-0.32022434,  0.02867257,  0.37149337, -0.17225952, -1.96147814,
         1.3652634 ]])

In [0]:
np.std(array)

1.2518152605528647

In [0]:
np.mean(array)

0.11470582173077938

In [0]:
sports = np.array(['golf', 'cric', 'fball', 'cric', 'Cric', 'fooseball'])

np.unique(sports)

array(['Cric', 'cric', 'fball', 'fooseball', 'golf'],
      dtype='<U9')

In [0]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [0]:
simple_array = np.arange(0,20)

In [0]:
simple_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [0]:
np.save('sample_array', sample_array)

In [0]:
np.savez('2_arrays.npz', a=sample_array, b=simple_array)

In [0]:
np.load('sample_array.npy')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [0]:
archive = np.load('2_arrays.npz')

In [0]:
archive['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [0]:
np.savetxt('text_file.txt', sample_array,delimiter=',')

In [0]:
np.loadtxt('text_file.txt', delimiter=',')

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.])